# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '瀑布流测试' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 瀑布流测试
pod "MJExtension"
pod "MJRefresh"
pod "SDWebImage"

  target '瀑布流测试Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '瀑布流测试UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
